# Web server options
webServerOptions:
    port: 8080
    username: "admin"
    password: "admin"
# Enable app logging
enableLogging: true
enableConsoleLogging: true
logDir: "logs"
logFile: "zlime.log"

dataDir: "data"
blocklistPath: "data/blocklist.txt"
allowlistPath: "data/allowlist.txt"


